---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Indexed read-only documents shared by native data providers and Lua-created windows.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.document
local document = {}

--- Index plain text once without creating a Lua table or buffer line per row. Attach the result with `win:document(source)` for viewport-only rendering and Vim navigation.
---@type fun(text: string): smelt.document.Document
document.text = nil

return document
