---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Composable layout-tree primitives for the retained main TUI layout. `smelt.ui.layout.set(fn)` registers a composer; call `invalidate()` when closed-over state changes the resulting tree.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.ui.layout
local ui_layout = {}

--- Wrap a subtree in optional border, title and padding. Natural size is the child's demand plus chrome; the child fills the inset area when the parent grows. Unlike a box slot, no fit/fill constraint is needed. Child chrome and shared split positions remain intact.
---@type fun(node: smelt.ui.layout, opts: table?): smelt.ui.layout
ui_layout.frame = nil

--- Horizontal container. `items` is an array of `{ child_layout, width = <constraint>, collapse_when_empty = bool? }`. `opts` accepts `border`, `title`, `gap`, `justify = "space-between"`, `padding` (uniform inner inset on all sides, inside any border).
---@type fun(items: table, opts: table?): smelt.ui.layout
ui_layout.hbox = nil

--- Place two subtrees side by side with a draggable divider. Retain this node across composer calls to preserve sizing. For independently rebuilt children or direct size control, use layout.split("horizontal", opts) and handle:layout(first, second). win:resize("width", delta) targets the nearest enclosing horizontal split.
---@type fun(first: smelt.ui.layout, second: smelt.ui.layout, opts: smelt.ui.layout.SplitOpts?): smelt.ui.layout
ui_layout.hsplit = nil

--- Invalidate the retained main layout so its composer runs during the next frame. Use this after changing closed-over state that affects layout structure or constraints.
---@type fun(): nil
ui_layout.invalidate = nil

--- Wrap a Win handle or paint id into a leaf node. `opts` accepts `border`, `title`, `collapse_when_empty` (force the slot to zero size when the wrapped window's buffer is empty), `measure` (a `{w, h}` table for a static natural size or a `smelt.ui.layout.measure(...)` handle for one the plugin can live-update).
---@see smelt.ui.layout.measure
---@type fun(win_or_paint: any, opts: table?): smelt.ui.layout
ui_layout.leaf = nil

--- Construct a shareable natural-size handle for use with `smelt.ui.layout.leaf(opts.measure = ...)`. Initial size is `(w, h)` (default `(0, 0)`); update at any time via `handle:set(w, h)` to drive a live resize on the next frame. Read current size via `handle:get()`.
---@type fun(w: integer?, h: integer?): smelt.ui.layout.Measure
ui_layout.measure = nil

--- Register the retained main layout composer. The callback receives a state table (`term_w`, `term_h`, `prompt_input_rows`, plus `dialog` while a root dialog is active) and returns a layout userdata built via `smelt.ui.layout.{vbox,hbox,leaf}`. `state.dialog` is an opaque transcript-dialog stage with host-owned sizing and expansion behavior. While a root dialog is active, the returned tree must include the current stage exactly once and no retained dialog stages from earlier calls; otherwise the host uses the safe transcript-dialog-statusline fallback. Passing `nil` clears the composer and reverts to the engine's hardcoded layout. The tree is retained until dimensions change or `smelt.ui.layout.invalidate()` is called.
---@see smelt.ui.layout.invalidate
---@type fun(composer: function?): nil
ui_layout.set = nil

--- Create a retained split handle independent of its children. axis is horizontal (side by side) or vertical (stacked). Use handle:layout(first, second, chrome_opts) in composers; rebuilding children preserves sizing. Handle methods inspect, restore, reset, resize, or equalize this exact split.
---@type fun(axis: string, opts: smelt.ui.layout.SplitOpts?): smelt.ui.layout.Split
ui_layout.split = nil

--- Vertical container. `items` is an array of `{ child_layout, height = <constraint>, collapse_when_empty = bool? }`. `opts` accepts `border`, `title`, `gap` (minimum cells between children), `justify = "space-between"` (put surplus cells into gaps), `padding` (uniform inner inset on all sides, inside any border).
---@type fun(items: table, opts: table?): smelt.ui.layout
ui_layout.vbox = nil

--- Stack two subtrees with a draggable divider. Retain this node across composer calls to preserve sizing. For independently rebuilt children or direct size control, use layout.split("vertical", opts) and handle:layout(first, second). win:resize("height", delta) targets the nearest enclosing vertical split.
---@type fun(first: smelt.ui.layout, second: smelt.ui.layout, opts: smelt.ui.layout.SplitOpts?): smelt.ui.layout
ui_layout.vsplit = nil

--- Return a layout's live window leaves in declaration order, excluding paints and repeated windows. Useful for installing shared callbacks and composing dialog bodies from arbitrary layouts.
---@type fun(node: smelt.ui.layout): smelt.win.Win[]
ui_layout.windows = nil

return ui_layout
